
spring:
  application:
    name: Product Service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: MahesH1516@
    
  
  boot:
    admin:
      client:
        url: http://localhost:1111/applications
     
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  cloud:
    config:
      enabled: false
    
    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eurekaServiceUrlPollIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

      

management:
  endpoints:
    web:
      exposure:
        include: '*'  
    
server:
  port: 3333
 
  

  

productservice :  
    message: 
     categoryAdded: Category Added Successfully
     categoryAddErr: Failed to Add Category
     categoryUpdate: Category Updated Successfully
     categoryUpdateErr: Failed to update category
     categoryFetch: All Categories fetched successfully
     categoryFetchErr: Failed to fetch all categories
     categorySelect: Category Retrieved Successfully
     categorySelectErr: Failed to retrieve category
     categoryDelete: Category deleted successfully
     categoryDeleteErr: Failed to delete category
     productAdded: Product Added Successfully
     productAddErr: Failed to Add Product
     productUpdate: Product Updated Successfully
     productUpdateErr: Failed to update Product
     productFetch: All Products fetched successfully
     productFetchErr: Failed to fetch all Products
     productSelect: Product Retrieved Successfully
     productSelectErr: Failed to retrieve Product
     productDelete: Product deleted successfully
     productDeleteErr: Failed to delete Product
     productStock: product stock updated
     productStockErr: product stock failed
    
  

  
  
  


  
  
  
 


  