
spring:
  application:
    name: Auth Service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: MahesH1516@
    
  
  boot:
    admin:
      client:
        url: http://localhost:1111/applications
     
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  cloud:
    config:
      enabled: false
      
    
    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eurekaServiceUrlPollIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

      

management:
  endpoints:
    web:
      exposure:
        include: '*'  
    
server:
  port: 4444
 

     
authservice:
  message:
   userReg: User Created
   userRegErr: User Creation Failed
   login: Login Success
   loginErr: Invalid Credentials
    

 
  
  
  
  
  
  
  
  
  
  
  
  
  
  