spring:
  application:
    name: CartService
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
Cart:
  message:
    cartAddSucc: Added to cart sucessfully
    cartAddErr: Error to Add to cart
    cartUpdateSucc: Cart Updated Sucessfully
    cartUpdateErr: Cart Updated Error
    CartRetBYUsingUserIdSucc: Retired Cart by Using user Id
    CartRetBYUsingUserIdErr: Error to Retired Cart by Using user Id
    CartDelSucc: Deleted cart by Id
    CartDelErr: Error to Deleted the cart
